#chateauDefaite
Je n'étais pas prêt...
Comment ai-je pu croire le contraire ?
Je craignais que la porte demeure close, que je ne puisse pas sortir du château, mais elle s'est ouverte à mon approche affolée...
Et maintenant, je cours à en perdre halène..
Tant pis pour mon honneur, tant pis pour ma mission, tant pis pour mon rêveur, je cours pour sauver ma peau...
Trempé jusqu'aux os par la pluie battante, j'entretiens l'espoir que l'Organiste va m'épargner, jusqu'à ce que des aboiements derrière moi me fasse tourner la tête...
luminio: Non ! Non !